# Test Database Configuration
spring.datasource.url=${TEST_DB_URL}
spring.datasource.username=${TEST_DB_USERNAME}
spring.datasource.password=${TEST_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
