spring.application.name=nudge
spring.profiles.active=dev

# Suppress warning about UserDetailsService with custom AuthenticationProvider
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
